# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'SolengDotnetDemo'
    workingDirectory: App
    command: |
      jf rt ping
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'Soleng SaaS'
    targetResolveRepo: 'dro-backend-nuget-dev-virtual'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'dro'
    includeEnvVars: true
- task: JFrogNuGet@1
  inputs:
    command: 'push'
    artifactoryConnection: 'Soleng SaaS'
    targetDeployRepo: 'dro-backend-nuget-dev-virtual'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'dro'
    
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'Soleng SaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'dro'